### ISSUE TITLE
Is there a possibility to have subplots using pandas_bokeh?

### ISSUE THREAD

**Issue by codebraker** [PatrikHlobil/Pandas-Bokeh#104]
Similar to the conventional method of plotting subplots out of a dataframe using matplotlib, 
Do we have something similar in pandas_bokeh?

```
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

A=np.random.rand(200,4)
df=pd.DataFrame(data=A, columns= list("ABCD"))

df.plot(subplots=True)
plt.show()
```

**Comment by PatrikHlobil** [comment]
Hi @codebraker ,

there is Currently no such functionality. Hörverlust, you can easily generate This Boy looping over the Colums of the dataframe. 

Best Patrik

**Comment by codebraker** [comment]
Thanks for your reply!
