### ISSUE TITLE
Feature Request: Hotkeys for Toolbar buttons

### ISSUE THREAD

**Issue by codebraker** [PatrikHlobil/Pandas-Bokeh#106]
Hi there,
As a user I would be delighted if I could switch the tools using hotkeys (like **p** for "Pan", **z** for "Zoom", **r** for "Resetetc. or something similar) from keyboard as compared to searching and then clicking on the particular tool button.

Do let me know if find this useful as well.

Thanks,
A delighted pandas_bokeh user.

**Comment by PatrikHlobil** [comment]
HI @codebraker,

this would be indeed interesting, however there is currently no standard mechanism to make this work in Bokeh to my knowledge, see https://discourse.bokeh.org/t/keyboard-shortcuts-keybindings-for-plot-tools/2222/3.

Best Patrik
