### ISSUE TITLE
Incorrect width:height scale of polygons

### ISSUE THREAD

**Issue by ozsharfr** [PatrikHlobil/Pandas-Bokeh#108]
Hi,
I'm visualizing my own polygons (as I mentioned - not related to countries). 
However, the dimensions of the polygons are very different than how they should look like (i.e. 3:1 length:Width instead of ~1:1). How can I scale it?
Thank you

**Comment by PatrikHlobil** [comment]
Hi @ozsharfr ,

Pandas-Bokeh's map functionality is actually build for plotting latitude/longitude coordinates/lines/polygons on a world map and does some transformation to match the geolocation with the map tiles.

For your use case, I would advice you to use the default Bokeh polygon plotting mechanism.

Best Patrik
