### ISSUE TITLE
Issue with Increasing Font Size of Tick Values on Cloropleth Color Bar

### ISSUE THREAD

**Issue by john-chau** [PatrikHlobil/Pandas-Bokeh#110]
I'm trying to increase the font size of the tick values of the color bar but I can't seem to find the correct way to do this. Could someone please advise? The code used is provided below:

p = df.plot_bokeh(simplify_shapes=10,
category=“x”,
colormap=list(Blues[6]).reverse(),
hovertool_columns=[“CFSAUID”, “y”, “z”],
figsize = (800,800),
colorbar_tick_format=“0%”)

**Comment by PatrikHlobil** [comment]
Hi @john-chau , 

you can try to use the bokeh object to find the corresponding colormap object and to set the property (I don't know where exactly to find it in the attributes). You can do so by:

```python
p = df.plot_bokeh(simplify_shapes=10,
category=“x”,
colormap=list(Blues[6]).reverse(),
hovertool_columns=[“CFSAUID”, “y”, “z”],
figsize = (800,800),
colorbar_tick_format=“0%”,
show_figure=True)

colormap_object = p.{access_attribute_here}

pandas_bokeh.show(p)

```

Best Patrik
