### ISSUE TITLE
Add option to x axis BoxZoomTool

### ISSUE THREAD

**Issue by ItamarShDev** [PatrikHlobil/Pandas-Bokeh#116]
Currently we can set `zooming=True`, which adds 2 axes BoxZoomTool.

Can we have the option to select the directions?

**Comment by PatrikHlobil** [comment]
hi @ItamarShDev,

do you mean that scrolling only should adjust the scale of the x or y axis?

Best Patrik

**Comment by ItamarShDev** [comment]
Yes @PatrikHlobil .
