### ISSUE TITLE
How to use formatter with custom hovertool_string.

### ISSUE THREAD

**Issue by fx-kirin** [PatrikHlobil/Pandas-Bokeh#13]
I'd like to use custom `Datetime` format for hovertool_string.But, it seems there is no way to define formatter from outside. Could you tell me how to use it?

https://github.com/PatrikHlobil/Pandas-Bokeh/blob/8fc99b49af46d95382dc18b8cc87f2d850e27b18/pandas_bokeh/plot.py#L964

    import pandas_bokeh
    import numpy as np
    import pandas as pd
    pandas_bokeh.output_file('sample.html')

    rng = pd.date_range('2015-02-24', periods=5, freq='T')
    df = pd.DataFrame({'Date': rng, 'Val': np.random.randn(len(rng))})
    df.index = df['Date']
    del df['Date']
    df.plot_bokeh(hovertool_string='@__x__values_original{%F}')

**Comment by PatrikHlobil** [comment]
Hi, 

you can use the following code:

```python
import pandas_bokeh
import numpy as np
import pandas as pd
pandas_bokeh.output_notebook()

rng = pd.date_range('2015-02-24', periods=5, freq='T')
df = pd.DataFrame({'Date': rng, 'Val': np.random.randn(len(rng))})
df.index = df['Date']
del df['Date']

p = df.plot_bokeh(hovertool=False, show_figure=False)

from bokeh.models import HoverTool
h = HoverTool(mode="vline")
h.tooltips = "@__x__values_original{%Y-%m-%d %H:%M:%S}"
h.formatters = {"__x__values_original": "datetime"}
p.add_tools(h)
pandas_bokeh.show(p)
````

You can use the standard c-like datetime string formatting (https://www.programiz.com/python-programming/datetime/strftime) here and get a plot like this:

![scroll](https://user-images.githubusercontent.com/31643597/54886170-27fcb300-4e85-11e9-9799-a57143fcee73.gif)

Hope I could help you,

Best Patrik

**Comment by fx-kirin** [comment]
Wow, thank you!!
