### ISSUE TITLE
Plotting LineString

### ISSUE THREAD

**Issue by BatchenE** [PatrikHlobil/Pandas-Bokeh#14]
Hi,

I think there's a bug when setting a geopandas LineString column as the geometry column, and running gdf.plot_bokeh()
if the column name isn't 'geometry' we get an error 'geometry not in index' 
only after i changes the column name to geometry I got the plot 
actually I think this happens not just for LineString also for 'regular' Point..
`gdf['return_point'] = [Point(xy) for xy in zip(gdf["return_lng"],gdf["return_lat"])]
gdf['take_point'] = [Point(xy) for xy in zip(gdf["take_lng"],gdf["take_lat"])]
gdf['line'] = [LineString(ab) for ab in zip (gdf["take_point"], gdf["return_point"])]
gdf.set_geometry('line',inplace=True)
gdf.crs = {'init' :'epsg:4326'}
#gdf.plot_bokeh()
test= gpd.GeoDataFrame(gdf,geometry='line')
test.crs = {'init' :'epsg:4326'}
test = test.rename(columns={'line': 'geometry'}).set_geometry('geometry')
test.plot_bokeh()`

**Comment by PatrikHlobil** [comment]
Hi,

thanks for the bug report. Never considered the case that you wouldn't call your geometry column "geometry". Should be an easy fix, but I haven't got any time right now. Hope that I can fix that soon. Hope you can live with your workaround.

Best Patrik

**Comment by PatrikHlobil** [comment]
Hi @BatchenE,

in the next release there will be a "geometry_column" parameter for plotting GeoDataFrames with geometry-columns of a different name than "geometry".

I would close this issue if this is okay for you.

Best Patrik
