### ISSUE TITLE
Shapely exception plotting maps

### ISSUE THREAD

**Issue by h-stivalet** [PatrikHlobil/Pandas-Bokeh#15]
Hello Patrik, 

I'm looking at your awesome library. I ran into an issue while testing the states' map examples (not sure if this is a bug, I'm new at all these geo localization stuff):

```
import requests
import geopandas as gpd
import pandas as pd
import pandas_bokeh
pandas_bokeh.output_file("map_states.html")

#Read in GeoJSON from URL:
df_states = gpd.read_file(r"https://raw.githubusercontent.com/PatrikHlobil/Pandas-Bokeh/master/Documentation/Testdata/states/states.geojson")
df_states.head()

df_states.plot_bokeh(simplify_shapes=10000)
```

I got the exception: 

> raise ValueError("No Shapely geometry can be created from null value")

I'm not sure what I'm missing here. It also happens with other examples.

Cheers

**Comment by PatrikHlobil** [comment]
Hi Hector,

nice to hear that you enjoy working with Pandas Bokeh. I do barely have any time to mantain the project right now, but could you tell me at which point this exception occurs. For me it seems as if this happens at

`df_states = gpd.read_file(r"https://raw.githubusercontent.com/PatrikHlobil/Pandas-Bokeh/master/Documentation/Testdata/states/states.geojson")
`

Is this right? I had issues like this before and probably it comes from a bad geojson format.

Best,

Patrik

**Comment by h-stivalet** [comment]
Hi Patrik,

Thank you for your answer. On that example I had tried changing the data source and it continued happening. However the example of the population map worked well.
I'll keep digging into this issue and if I solve it I'll feed this entrance.

I wasn't informed yesterday why I was told to take a look over this library. Today I know it's to obtain traffic reports of my city taking the data from the DB of the maps app called Waze to draw it as a public information. It really seems to be a lot of fun.

Cheers

**Comment by PatrikHlobil** [comment]
Hi Hector,

In this case, you probably want to look at the pandas.dataframe.plot_bokeh.map method provided by Pandas Bokeh.

But note that drawing many points on a map (>100000) May result in a poor performance of the plot.

How many data points do you have?

**Comment by h-stivalet** [comment]
Hi Patrik,

As a first glance to the traffic report, yesterday records count is 30,000 lines that varies in distance with an estimate average of 12 points per line. There are other tables with reports (accidents, potholes, etc) that represents points with 77027 points reported yesterday.

I may have to draw this data dynamically based on day hours.

**Comment by PatrikHlobil** [comment]
Ok, I think you can use Pandas Bokeh for that. You May want to look at the slider functionality ...

Alternatively, you could may find this interesting:

https://youtu.be/GOE__moR0eo

By the way, I looked at the problem above. I think the problem is that GeoPandas has a problem to properly parse and convert the Geojson to a shapely object.

**Comment by PatrikHlobil** [comment]
@h-stivalet : I fixed the bug you reported. It was however in the data and Alaska had a bad representation, such that I deleted it from the data set. 

The code snippet from the documentation

```python
import requests
import geopandas as gpd
import pandas as pd
import pandas_bokeh
pandas_bokeh.output_file("map_states.html")

#Read in GeoJSON from URL:
df_states = gpd.read_file(r"https://raw.githubusercontent.com/PatrikHlobil/Pandas-Bokeh/master/Documentation/Testdata/states/states.geojson")
df_states.head()

df_states.plot_bokeh(simplify_shapes=10000)
```

works now for me.

Best, Patrik
