### ISSUE TITLE
Select cities to visualize

### ISSUE THREAD

**Issue by emanuelemassaro** [PatrikHlobil/Pandas-Bokeh#24]
Is it possible to select and visualize cities based on selections?

**Comment by PatrikHlobil** [comment]
Hi @emanuelemassaro ,

I am pretty sure that this would be possible. However, could you be more specific and maybe give me a minimal example code & data?

Cheers, Patrik

**Comment by emanuelemassaro** [comment]
Sure:

```
schools = gpd.read_file('myPoints.shp')
schools = schools.to_crs({'init': 'epsg:4326'})
boundary = gpd.read_file('boundary.shp')
boundary = boundary.to_crs({'init': 'epsg:4326'})

figure = boundary.plot_bokeh(
        simplify_shapes=10000,
        hovertool_string="""<h2> @{ADM2_EN} </h2> """, show_figure=False)
schools.plot_bokeh(figure=figure)
```

Where boundary looks like the following:

![Uploading Screen Shot 2019-05-20 at 15.26.34.png…]()

**Comment by PatrikHlobil** [comment]
Hm, the uploaded picture doesn't seem to work. Could you provide me your data? This would be easier for me.

**Comment by emanuelemassaro** [comment]
Hi,

here the code you can use. You can download the shapefile [here](https://data.world/ocha-haiti/777e8b06-337f-4295-80bc-ca1515244215) or I can send it to you.

```
import geopandas as gpd
import pandas as pd

import pandas_bokeh
pandas_bokeh.output_notebook()

import shapely

from bokeh.tile_providers import get_provider, Vendors
get_provider(Vendors.CARTODBPOSITRON)
get_provider('CARTODBPOSITRON')


## Load Shapefile
boundary = gpd.read_file('hti_admbnda_adm2_cnigs_20181129.shp')
boundary = boundary.to_crs({'init': 'epsg:4326'})


## Collect data from omsnx and clean it
import osmnx as ox
selected_amenities = ['school']
place = 'Haiti'
schoolOSM = ox.pois_from_place(place=place, amenities=selected_amenities)
schools = gpd.GeoDataFrame(schoolOSM)
idxok = []
for i in schools.index:
    if type(schools['geometry'][i]) == shapely.geometry.point.Point:
        idxok.append(i)
schools = schools[schools.index.isin(idxok)]
schools = gpd.GeoDataFrame(schools)
schools.crs = {'init' :'epsg:4326'}


figure = boundary.plot_bokeh(
        figsize=(900, 600),
        simplify_shapes=10000,
        hovertool_string="""<h2> @{ADM2_EN} </h2> """, show_figure=False)
schools.plot_bokeh(figure=figure)
```

**Comment by PatrikHlobil** [comment]
Hi @emanuelemassaro,

sorry for not responding to your issue, but I had a lot to do in the past month. I finally came to look at your issue again, but couldn't easily download the data you provided, however, I prepared an example how you could select cities like this. 

![test](https://user-images.githubusercontent.com/31643597/60619051-0beba480-9dd8-11e9-89b0-bf2a298bde6d.gif)

Just download this zip-file:
[example city selection.zip](https://github.com/PatrikHlobil/Pandas-Bokeh/files/3356519/example.city.selection.zip)

where you can find a jupyter notebook and the corresponding data for the example.

Hope this helps you. Please tell me if this solves your problem?

Best,

Patrik

**Comment by PatrikHlobil** [comment]
@emanuelemassaro : I will now close this issue. Best Patrik
