### ISSUE TITLE
Attribute Error in DataFrames

### ISSUE THREAD

**Issue by NRGPlus79** [PatrikHlobil/Pandas-Bokeh#39]
Hello,

I am currently running Numpy v1.15.4, Pandas v0.23.4, Pandas-Bokeh v0.3.1 and find the following error as I run the example code:

import numpy as np
import pandas as pd

np.random.seed(42)
df = pd.DataFrame({"Google": np.random.randn(1000)+0.2, 
                   "Apple": np.random.randn(1000)+0.17}, 
                   index=pd.date_range('1/1/2000', periods=1000))
df = df.cumsum()
df = df + 50
df.plot_bokeh(kind="line") 

AttributeError: 'FramePlotMethods' object has no attribute '_data'

Checking previous issues I saw this could have been fixed in the latest version, but maybe not yet? The above issue is not present in Series objects. Any help will be appreciated.

Many thanks for this useful package!

**Comment by PatrikHlobil** [comment]
Hi @NRGPlus79,

Thanks for reporting this issue.
Are you sure you are using pandas-bokeh 0.3.1, because the current release is 0.3?

Best Patrik

**Comment by NRGPlus79** [comment]
Hello Patrick!

Thanks for the follow up. I tried 0.3 and got the same issue. That's why I installed the latest developer version (0.3.1). The issue persisted.

Many thanks again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PatrikHlobil** [comment]
Hi @NRGPlus79,

Ok. I guess I know what the problem is, For the most recent version 0.25 of pandas I had to do a lot of refactoring and changes. I will try to fix this bug as early as possible, but I’m on vacation right now and have no computer.

Thanks again for reporting the bug 😉.

Best Patrik

**Comment by PatrikHlobil** [comment]
PS: i just fixed the issue (at least I hope so). @NRGPlus79 , could you please test if the current development version works for you?

**Comment by NRGPlus79** [comment]
Hello Patrik. Many thanks again. Unfortunately I get the same error. Let me share the full detail with you:


---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-6-16db8273bbf7> in <module>

      7 df = df.cumsum()

      8 df = df + 50

----> 9 df.plot_bokeh(kind="line")



~\Anaconda3\lib\site-packages\pandas_bokeh\plot.py in __call__(self, *args, **kwargs)

   1735

   1736     def __call__(self, *args, **kwargs):

-> 1737         return plot(self.df, *args, **kwargs)

   1738

   1739     @property



~\Anaconda3\lib\site-packages\pandas_bokeh\plot.py in df(self)

   1743             dataframe = self._parent

   1744         else:

-> 1745             dataframe = self._data

   1746

   1747         # Convert PySpark Dataframe to Pandas Dataframe:



AttributeError: 'FramePlotMethods' object has no attribute '_data'


Hope this helps.
Regards.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by PatrikHlobil** [comment]
Hi @NRGPlus79 ,

I could not reproduce your problem with the current master on Github. It works fine for me:

![image](https://user-images.githubusercontent.com/31643597/64080894-6a120680-ccf9-11e9-8721-edde861e0533.png)

Could you please reinstall your Pandas-Bokeh version to the current git master and try again ;).

Best Patrik

**Comment by NRGPlus79** [comment]
Hello Patrik,

Many thanks for the follow up. I found this issue in Pandas v 0.23.4, so one version ahead of yours.

I rolled back my Pandas so I have no issues now, but this is  sign that maybe ulterior versions of Panda might bring some issues to this library.


Keep the good work!
Many thanks again.
________________________________
De: Patrik Hlobil <notifications@github.com>
Enviado: domingo, 1 de septiembre de 2019 07:46 p. m.
Para: PatrikHlobil/Pandas-Bokeh <Pandas-Bokeh@noreply.github.com>
CC: NRGPlus79 <rafael_guitart@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [PatrikHlobil/Pandas-Bokeh] Attribute Error in DataFrames (#39)


Hi @NRGPlus79<https://github.com/NRGPlus79> ,

I could not reproduce your problem with the current master on Github. It works fine for me:

[image]<https://user-images.githubusercontent.com/31643597/64080894-6a120680-ccf9-11e9-8721-edde861e0533.png>

Could you please reinstall your Pandas-Bokeh version to the current git master and try again ;).

Best Patrik

**Comment by NRGPlus79** [comment]
Hello Patrik,

One sensible improvement to the current pack would be the option to reverse the color palette. Unfortunately most palettes give a darker tone (higher presence) to darker colors.

See below how to reverse the palette upon import:

https://automating-gis-processes.github.io/2017/lessons/L5/advanced-bokeh.html

Look for this command:

palette.reverse()

Many thanks again!

________________________________
De: Rafael Adrián Guitart <rafael_guitart@hotmail.com>
Enviado: lunes, 2 de septiembre de 2019 12:50 p. m.
Para: PatrikHlobil/Pandas-Bokeh <reply@reply.github.com>
Asunto: Re: [PatrikHlobil/Pandas-Bokeh] Attribute Error in DataFrames (#39)

Hello Patrik,

Many thanks for the follow up. I found this issue in Pandas v 0.23.4, so one version ahead of yours.

I rolled back my Pandas so I have no issues now, but this is  sign that maybe ulterior versions of Panda might bring some issues to this library.


Keep the good work!
Many thanks again.
________________________________
De: Patrik Hlobil <notifications@github.com>
Enviado: domingo, 1 de septiembre de 2019 07:46 p. m.
Para: PatrikHlobil/Pandas-Bokeh <Pandas-Bokeh@noreply.github.com>
CC: NRGPlus79 <rafael_guitart@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [PatrikHlobil/Pandas-Bokeh] Attribute Error in DataFrames (#39)


Hi @NRGPlus79<https://github.com/NRGPlus79> ,

I could not reproduce your problem with the current master on Github. It works fine for me:

[image]<https://user-images.githubusercontent.com/31643597/64080894-6a120680-ccf9-11e9-8721-edde861e0533.png>

Could you please reinstall your Pandas-Bokeh version to the current git master and try again ;).

Best Patrik

**Comment by PatrikHlobil** [comment]
Hi @NRGPlus79 ,

This is a pretty good idea, thanks for sharing it 😉. I created a new issue #43 for this, maybe you want to work on it???

Best Patrik

**Comment by NRGPlus79** [comment]
Dear Patrik,

One quick question here: Say you produced a chart from a Pandas Dataframe. What would be the fastest way to update the source data for that chart without re-rendering the whole chart? Is there a way to access the source data like in any other Bokeh chart (like chart.data_source.data) and then update it? I tried in several ways but I could not find a workaround.


Many thanks again!
Regards.
________________________________
De: Patrik Hlobil <notifications@github.com>
Enviado: viernes, 20 de septiembre de 2019 04:37 p. m.
Para: PatrikHlobil/Pandas-Bokeh <Pandas-Bokeh@noreply.github.com>
CC: NRGPlus79 <rafael_guitart@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [PatrikHlobil/Pandas-Bokeh] Attribute Error in DataFrames (#39)


Hi @NRGPlus79<https://github.com/NRGPlus79> ,

This is a pretty good idea, thanks for sharing it 😉. I created a new issue #43<https://github.com/PatrikHlobil/Pandas-Bokeh/issues/43> for this, maybe you want to work on it???

Best Patrik
