### ISSUE TITLE
Lineplot Rangetool broken?

### ISSUE THREAD

**Issue by Kladderadatasch** [PatrikHlobil/Pandas-Bokeh#47]
Hi,
when I execute your sample code in Jupyter: 

```
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
df = pd.DataFrame(np.random.randn(1000, 4), index=ts.index, columns=list('ABCD'))
df = df.cumsum()
df.plot_bokeh(rangetool=True)
```

The following Error appears:

> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-17-ee1456589bb0> in <module>
>       3 df = df.cumsum()
>       4 
> ----> 5 df.plot_bokeh(rangetool=True)
> 
> ~/anaconda3/envs/E1lib/python3.7/site-packages/pandas_bokeh/plot.py in __call__(self, *args, **kwargs)
>    1735 
>    1736     def __call__(self, *args, **kwargs):
> -> 1737         return plot(self.df, *args, **kwargs)
>    1738 
>    1739     @property
> 
> ~/anaconda3/envs/E1/lib/python3.7/site-packages/pandas_bokeh/plot.py in plot(df_in, x, y, kind, figsize, use_index, title, legend, logx, logy, xlabel, ylabel, xticks, yticks, xlim, ylim, fontsize, color, colormap, category, histogram_type, stacked, weights, bins, normed, cumulative, show_average, plot_data_points, plot_data_points_size, number_format, disable_scientific_axes, show_figure, return_html, panning, zooming, toolbar_location, hovertool, hovertool_string, vertical_xlabel, webgl, **kwargs)
>     477             hovertool_string,
>     478             number_format,
> --> 479             **kwargs
>     480         )
>     481 
> 
> ~/anaconda3/envs/E1/lib/python3.7/site-packages/pandas_bokeh/plot.py in lineplot(p, source, data_cols, colormap, hovertool, xlabelname, x_axis_type, plot_data_points, plot_data_points_size, hovertool_string, number_format, **kwargs)
>    1013         hovertool_string=hovertool_string,
>    1014         number_format=number_format,
> -> 1015         **kwargs
>    1016     )
>    1017 
> 
> ~/anaconda3/envs/E1/lib/python3.7/site-packages/pandas_bokeh/plot.py in _base_lineplot(linetype, p, source, data_cols, colormap, hovertool, xlabelname, x_axis_type, plot_data_points, plot_data_points_size, hovertool_string, number_format, **kwargs)
>     951             source=source,
>     952             color=color,
> --> 953             **kwargs
>     954         )
>     955 
> 
> fakesource in line(self, x, y, **kwargs)
> 
> ~/anaconda3/envs/E1lib/python3.7/site-packages/bokeh/plotting/helpers.py in func(self, **kwargs)
>     855             mglyph_ca = None
>     856 
> --> 857         glyph = _make_glyph(glyphclass, kwargs, glyph_ca)
>     858         nsglyph = _make_glyph(glyphclass, kwargs, nsglyph_ca)
>     859         sglyph = _make_glyph(glyphclass, kwargs, sglyph_ca)
> 
> ~/anaconda3/envs/E1/lib/python3.7/site-packages/bokeh/plotting/helpers.py in _make_glyph(glyphclass, kws, extra)
>     396     kws = kws.copy()
>     397     kws.update(extra)
> --> 398     return glyphclass(**kws)
>     399 
>     400 
> 
> ~/anaconda3/envs/E1/lib/python3.7/site-packages/bokeh/model.py in __init__(self, **kwargs)
>     305         kwargs.pop("id", None)
>     306 
> --> 307         super(Model, self).__init__(**kwargs)
>     308         default_theme.apply_to_model(self)
>     309 
> 
> ~/anaconda3/envs/E1/lib/python3.7/site-packages/bokeh/core/has_props.py in __init__(self, **properties)
>     251 
>     252         for name, value in properties.items():
> --> 253             setattr(self, name, value)
>     254 
>     255     def __setattr__(self, name, value):
> 
> ~/anaconda3/envs/E1/lib/python3.7/site-packages/bokeh/core/has_props.py in __setattr__(self, name, value)
>     286 
>     287             raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
> --> 288                 (name, self.__class__.__name__, text, nice_join(matches)))
>     289 
>     290     def __str__(self):
> 
> AttributeError: unexpected attribute 'rangetool' to Line, possible attributes are 

> js_event_callbacks, js_property_callbacks, line_alpha, line_cap, line_color, line_dash, line_dash_offset, line_join, line_width, name, subscribed_events, tags, x or y

**Comment by PatrikHlobil** [comment]
Hi @Kladderadatasch ,

Thanks for reporting this issue. The reason is that the current documentation already contains features of the next release, which should be out soon. You can install the current dev version, which will be release 0.4 via:

    pip install git+https://github.com/PatrikHlobil/Pandas-Bokeh.git

Does it work then?

Best Patrik

**Comment by PatrikHlobil** [comment]
Hi @Kladderadatasch ,

Thanks for reporting this issue. The reason is that the current documentation already contains features of the next release, which should be out soon. You can install the current dev version, which will be release 0.4 via:

pip install git+https://github.com/PatrikHlobil/Pandas-Bokeh.git

**Comment by Kladderadatasch** [comment]
Hi @PatrikHlobil,
thanks for resolving this issue, indeed now the sample code works
and I could adjust it also to my needs. 
However, I've got a follow up issue:

The Rangetool takes automatically the DateTime index and represents it as
a well-formatted date. I.e. 2011/11/24
But if I use your lineplot and with code like
```
    hovertool_string=r"""                                        
                        <h3> Date: @{TIMESTAMP}</h3>
""",
```
I'm returned with a Unix timestamp, even the Index is in pandas datetime format. 
Is there a way to format this? Here in original bokeh with code like:

```
    formatters={
        'date'      : 'datetime', # use 'datetime' formatter for 'date' field
    }, 
```
I'm wondering how I can make fine adjustments like this for the hover tool and why 
the range tool has a different representation.

**Comment by Kladderadatasch** [comment]
EDIT: 
For the line plots I used
x = 'TIMESTAMP'
because if I set the timestamp here as index, 
the datetime of TIMESTAMP is replaced by the row-number in the plot, 
giving me a straight linear line.

**Comment by PatrikHlobil** [comment]
Hi @Kladderadatasch ,

the simplest solution that comes in my mind is that you define an additional column in your DataFrame, where you convert your timestamps using the simple pandas datetime functionalities in the string format that you wish and then you use this column in the hovertool_string.

Would that suit your needs?

Best,

Patrik

**Comment by Kladderadatasch** [comment]
@PatrikHlobil,

that was simple and great help, I'm a bit embaressed having not thought about this myself. 
Using the dataframe.dt.strftime('%Y-%m-%d, %H:%M:%S') function, I could display everything beautifully. 
Many thanks!

**Comment by PatrikHlobil** [comment]
Hi @Kladderadatasch ,

Good to hear that I could help you. I just released version 0.4 on PyPI, so you can now switch to the official version if you want.

Best Patrik

**Comment by Kladderadatasch** [comment]
Hi again @PatrikHlobil,

I guess there's a small issue with the PyPi packages.
If you install it via pip, you'll receive version 0.4, but through conda you'll receive version 0.3.
Maybe give that a check ?

Cheers

**Comment by PatrikHlobil** [comment]
Hi @Kladderadatasch ,

This is correct. With version 0.4 I have issues converting it to a conda package 😔. However since it is a pure python package, you can savely install it via pip.

Best Patrik
