### ISSUE TITLE
AttributeError: 'function' object has no attribute 

### ISSUE THREAD

**Issue by ronyarmon** [PatrikHlobil/Pandas-Bokeh#5]
Hi, I got AttributeError: 'function' object has no attribute 'area' for the Areaplot example and 
AttributeError: 'function' object has no attribute 'scatter' for the Iris scatter plot example. 

pandas and pandas_bokeh were imported.

**Comment by PatrikHlobil** [comment]
Hi, I cannot reproduce the problem with todays release 0.1. Please try to upgrade pandas-bokeh via:

    pip install --upgrade pandas-bokeh
