### ISSUE TITLE
Datetime hover tool shows UTC time by default

### ISSUE THREAD

**Issue by koti-Maddala** [PatrikHlobil/Pandas-Bokeh#50]
Hello Team,

I am plotting data on map using plot_bokeh.map(). Everyting seems to be working fine except date time column which is displaying UTC as default . I am using Hoevertool_columns to display the datetime when I hover over the points on map.

Could you please let me know how to fix this issue

**Comment by PatrikHlobil** [comment]
Hi @koti-Maddala ,

Could you please provide a minimal code example where This issue occurs?

 Best Patrik

**Comment by koti-Maddala** [comment]
Hello Patrick,

My bad, it was the default datetime issue on the server. It is fixed now :)
