### ISSUE TITLE
BokehDeprecationWarnings with Bokeh v1.4.0

### ISSUE THREAD

**Issue by lordsutch** [PatrikHlobil/Pandas-Bokeh#51]
The latest release of the Bokeh package has deprecated the `legend` keyword, so the output of all plots now includes the following message:

> BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead

**Comment by PatrikHlobil** [comment]
Hi @lordsutch ,

thanks for the bug report. I fixed the bug for the piecharts, but I also have to fix it for some other plots.

Best Patrik

**Comment by surfaceowl** [comment]
This example using lineplots also generates the BokehDeprecationWarning:

```
import bokeh
from bokeh.plotting import output_notebook
import pandas as pd

output_notebook()
pd.set_option('plotting.backend', 'pandas_bokeh')

ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2018', periods=1000))
df = pd.DataFrame(np.random.randn(1000, 4), index=ts.index, columns=["alpha", "bravo", "charlie", "delta"])
df = df.cumsum()

df.plot_bokeh(figsize=(1200, 450), rangetool=True)
```

**which returns:**
```
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead

...plus a great looking chart!
```

**Comment by joshyro** [comment]
Hello! I'm having this warning message too, it is necessary change legend to lengend_label in the source.

> BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead

In other case, It is possible to override legend_label?

**Comment by joshyro** [comment]
I've commented legend parameter
`legend=" " + name`
`#legend=" " + name`

and now I can add:
`legend_label='My label =)'`

I've tried to move if/else at the beggining of the code for fix the warnings but I didn't success.
 `if bokeh.__version__ < "1.4":
            legend_parameter_name = "legend"
        else:
            legend_parameter_name = "legend_label"`

**Comment by PatrikHlobil** [comment]
Hi, I already tried a quickfix for this but also didn't suceed. In the moment, I really have barely any time for maintaining, I'm sorry for that. I'll try to fix this as soon as possible.

**Comment by cybertk** [comment]
@PatrikHlobil Any good news?

**Comment by PatrikHlobil** [comment]
Hi @cybertk @lordsutch @joshyro ,

Yesterday I finally found some time to work on these deprecation messages. I could fix all issues, however I lost backwards compatibility with Bokeh and have to enforce bokeh>=2.0 in the future releases. Hope to release the fix this week.

Best Patrik

**Comment by PatrikHlobil** [comment]
Closed with version 0.5

**Comment by Harikumar9412-R** [comment]
from bokeh.plotting import figure, show, output_file

x = [1, 2, 4, 6, 7]
y = [3, 6, 9, 10, 15]

output_file("legend.html")

p = figure()
p.circle(x, y, legend_label="Quantity")
p.line(x, y, legend_label="Tax 5%")
p.line(x, y, legend_label="Quantity",
       line_dash=[4, 4], line_color="orange", line_width=2)
p.square(x, y, legend_label="Quantity", fill_color=None, line_color="green")
p.line(x, y, legend_label="Tax 5%", line_color="green")
show(p)

**Comment by PatrikHlobil** [comment]
Hi @Harikumar9412-R ,

could you please explain me why you added this comment in the issue?

Best Patrik

**Comment by arjungoel** [comment]
Hey @PatrikHlobil , I am also getting this warning `BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead` when using bokeh 2.3.0

Can you please tell the reason behind this?

Thanks

**Comment by PatrikHlobil** [comment]
Hello @arjungoel ,

which version of Pandas-Bokeh are you using?

Best Patrik

**Comment by arjungoel** [comment]
Hey @PatrikHlobil, I am using version 2.3.0

**Comment by PatrikHlobil** [comment]
@arjungoel,

this is a very outdated version. please try to upgrade to the most recent version 0.5.4 via:

     pip install -U pandas-bokeh

What version of Python are you using?

Best Patrik

**Comment by arjungoel** [comment]
Hey @PatrikHlobil , the Python version I have been working on is 3.9.0

**Comment by PatrikHlobil** [comment]
Hi @arjungoel ,

did upgrading pandas-bokeh solve your Issue?

Best Patrik
