### ISSUE TITLE
Ignore NaN value's in hovertool

### ISSUE THREAD

**Issue by Timthijssen** [PatrikHlobil/Pandas-Bokeh#53]
Hi,

I'm new to Bokeh and I'm trying to visualize customers throughout Europe and the corresponding prices that are used for 15 different products. To do this, I mapped the geolocations of every customer and I put the prices of each product in the hovertool.

It's almost works sufficiently, thanks to this great backend. However, i have the following problem:

Each customer only buys 1-8 different products.  This means that many prices contain NaN values. In the hovertool this results in '????' for the products that have no price for a specific customer.

In the hovertool, i simply specify a list of column names that should be included. Each column represents a product, which contains a price for each customer (row).

Is there any way i can ignore NaN values in the Hovertool? Or are there more advanced formatting tricks i can use?

Thanks!

**Comment by PatrikHlobil** [comment]
Hi @Timthijssen,

sounds like a nice visualization. I would succest that you just replace the NaN values by and empty string or 0 (depending what makes more sense to you) in the Pandas DataFrame. Does this solve your problem.

Best,

Patrik

**Comment by Timthijssen** [comment]
Hi Patrik,

Thanks for you quick response! It indeed removes the '???' values. However, I would preferibly only show a column in the hovertool if the value > 0. Would this be possible in any way?

Thanks!

**Comment by PatrikHlobil** [comment]
This is not directly possible. However, you could create a new column in your dataframe, where you just store a string in the way you want the hovertool to be (the hovertool also supports HTML as can be seen here https://github.com/PatrikHlobil/Pandas-Bokeh#advanced-lineplot, so you can do fancy stuff in it).

**Comment by PatrikHlobil** [comment]
Closed
