### ISSUE TITLE
hovertool datetime format

### ISSUE THREAD

**Issue by joshyro** [PatrikHlobil/Pandas-Bokeh#56]
Hello!
I getting stuck with hovertool datetime format, my df dtype is:

`history_days.dtypes` 
`Fecha    datetime64[ns]` 
`costo             int64`
`dtype: objec`

from Pandas-Bokeh:

`first_value = np.array(history_days)[0]`

`first_value`
`array([Timestamp('2019-12-31 00:00:00'), 1824], dtype=object)`

`isinstance(first_value, (np.datetime64, datetime.datetime, datetime.date))`
`False`

So, my bar is not showing hovertool with datetime format correctly, What am I missing?

**Comment by PatrikHlobil** [comment]
Hi @joshyro, 

Could you please provide a minimal code example of your problem?

Best Patrik

**Comment by PatrikHlobil** [comment]
Hi @joshyro,

I can not help you with this issue without more information. I will close this issue, but if this problem is still there for you, please open another issue and please give me a minimal working example,

Best Patrik
