### ISSUE TITLE
Pie plot legend_field

### ISSUE THREAD

**Issue by joshyro** [PatrikHlobil/Pandas-Bokeh#57]
Hello again!!!
I'm trying to use pie plot but legend_field is not displaying correctly, I'm using bokeh 1.4.0
![image](https://user-images.githubusercontent.com/461130/73575396-16d9e680-4446-11ea-8c78-d508eb96e7d0.png)

In other case, I've added layout option to bar plot :) Is this correctly? 

`p_zone = zone.plot_bokeh.bar(
    x='Zona',
    y='Importe',
    xlabel="Zona",
    ylabel='Importe',
    layout=[high_box, low_box],
    title='Ingreso por zonas',
    legend_label='Ingreso Zona',
    vertical_xlabel= True,
    alpha=0.8,
    legend = "top_left",
    panning=False,
    zooming=False,
    show_figure=True)`

![image](https://user-images.githubusercontent.com/461130/73575785-ea729a00-4446-11ea-84bc-1bd0f35992dd.png)

**Comment by PatrikHlobil** [comment]
This is probably a problem with the api changes of Bokeh itself, See also #51 . I’ll try to fix this soon. Thanks for reporting,

Best Patrik

**Comment by PatrikHlobil** [comment]
Hi @joshyro,

thanks again for reporting. I fixed the issue today (see #82 ) and it should soon be released with version 0.5.1

Best Patrik
