### ISSUE TITLE
Bokeh 2.0 is imminent

### ISSUE THREAD

**Issue by bryevdv** [PatrikHlobil/Pandas-Bokeh#59]
Just a heads-up that Bokeh 2.0 will be coming out in the next week or so. At a minimum you may want to release packages that versions to <2.0 if they are not already. Whenever you look to update packages for Bokeh 2.0 compat we'd be happy to help over at the Development topic on the Discourse:

https://discourse.bokeh.org/c/development/7

**Comment by PatrikHlobil** [comment]
Hi @bryevdv ,

pandas-bokeh works fine with Bokeh 2.0, however there are some deprecation messages. I'll try to fix that soon.

Best Patrik
