### ISSUE TITLE
Legend issues with pandas-bokeh

### ISSUE THREAD

**Issue by nrapanos** [PatrikHlobil/Pandas-Bokeh#66]
Hello - I am experiencing the following issues with pandas_bokeh:

1. When I plot a large number of timeseries, the legend reaches the maximum number and does not allow scrolling to reveal the rest of the timeseries that have been plotted.
2. Datetime works on the x-axis but on hover it is interpreted in a weird format.

The following plot demonstrates both problems.

![bokeh](https://user-images.githubusercontent.com/2314096/81786441-8fe1e300-94f7-11ea-9d67-bcebfe1d1eae.PNG)

**Comment by PatrikHlobil** [comment]
Hi @nrapanos,

thanks for your feedback.

1. There is no scroll option available so far for legends in Bokeh. However, I will add a legend_fontsize option in the next release of Pandas-Bokeh (0.5), but for now, you can just do
```python
p = df.plot_bokeh(..., show_figure=False)

p.legend.label_text_font_size = "8px"

pandas_bokeh.show(p)
```

2. This is an issue with the most recent Bokeh version (>=2.0). Please upgrade Pandas-Bokeh to 0.4.3 to fix that datetime hover problem.

Best Patrik

**Comment by nrapanos** [comment]
Thank you, Patrick.

On the second issue, I am using the most recent version and I tried some sample code as well.

N

**Comment by PatrikHlobil** [comment]
Ok. Can you do a pip list on the command line please?

Best Patrik

**Comment by nrapanos** [comment]
Hey Patrik – here you are:

[cid:image001.png@01D62921.CC34F2D0]

[cid:image002.png@01D62921.CC34F2D0]

**Comment by PatrikHlobil** [comment]
Hi, 

unfortunately the images are not correctly shown...

**Comment by nrapanos** [comment]
Ah sorry - so I have bokeh 2.0.1 and pandas-bokeh 0.4.3.

Nikolaos P. Rapanos


On 13 May 2020, at 14:28, Patrik Hlobil <notifications@github.com> wrote:

﻿
This email from notifications@github.com originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Hi,

unfortunately the images are not correctly shown...

**Comment by PatrikHlobil** [comment]
Thanks, the dependencies should be fine. Could you give a minimal code example where you see the hovertool issues please?

Using the following example I see the dates correctly displayed in the hovertool:
```python
import pandas as pd
import pandas_bokeh
pandas_bokeh.output_notebook()

import numpy as np

np.random.seed(42)
df = pd.DataFrame({"Google": np.random.randn(1000)+0.2, 
                   "Apple": np.random.randn(1000)+0.17}, 
                   index=pd.date_range('1/1/2000', periods=1000))
df = df.cumsum()
df = df + 50
df.plot_bokeh(kind="line")   
```

Best Patrik

**Comment by nrapanos** [comment]
hmm interesting...this is that I get. i will investigate a bit on my end.

![temp](https://user-images.githubusercontent.com/2314096/81827157-67c2a600-9530-11ea-90a2-9c17088f791b.PNG)

**Comment by PatrikHlobil** [comment]
Maybe try to reload the Kernel?

**Comment by nrapanos** [comment]
I tried that many times, I even closed my PyCharm and rebooted, but the problem persists. 
It's ok, to be honest it doesn't bother me very much. 

On another note, do you think we could ask the bokeh community to allow the legend to be scrollable? That would be more important to me.

**Comment by PatrikHlobil** [comment]
Sure, you can always ask for a feature. I think it is a good idea, however a pretty narrow usecase. Best Patrik
