### ISSUE TITLE
Not compatible with Bokeh 2.x

### ISSUE THREAD

**Issue by manisekhar-kothuri** [PatrikHlobil/Pandas-Bokeh#68]
Hi Patrick,

Sliders and dropdowns are not working with Bokeh 2.x .

**Comment by PatrikHlobil** [comment]
Hi @manisekhar-kothuri ,

Thanks for reporting this. I will have a look at the issue .

Best Patrik

**Comment by PatrikHlobil** [comment]
Hi @manisekhar-kothuri,

I fixed the slider and dropdown. again thanks for reporting. I will try to get the release out as soon as possible.

Best Patrik

**Comment by manisekhar-kothuri** [comment]
Hi Patrik,

Can you tell me why slider is not working?

**Comment by PatrikHlobil** [comment]
Hi @manisekhar-kothuri,

The following commit https://github.com/PatrikHlobil/Pandas-Bokeh/commit/39f6a40aa76d8965335cdef6185442e02b01471b fixed the issue. there was a Problem with the JavaScript That defines the callback of the slider. 

Best Patrik
