### ISSUE TITLE
Data type not understood

### ISSUE THREAD

**Issue by makermotion** [PatrikHlobil/Pandas-Bokeh#70]
config:
  virtualenv:
  - python v.3.8 
  - pandas-bokeh v.0.5
  - geopandas 0.7.0
  
 .geojson:
  Created via https://geojson-maps.ash.ms/ (with all continents selected)

  error:
  TypeError: Data type not understood

P.s. It works with exactly same config but pandas-bokeh v.4.3

**Comment by PatrikHlobil** [comment]
Hi @lmaskedpiratel,

thanks for reporting. Could you provide me the exact geojson file and code that raises the error please.

Best Patrik

**Comment by lmaskedpiratel** [comment]
Hey,

geojson:
[geo.tar.gz](https://github.com/PatrikHlobil/Pandas-Bokeh/files/4700555/geo.tar.gz)

and the code was nothing special:

import geopandas as gpd
import pandas_bokeh
pandas_bokeh.output_notebook()
import pandas as pd
pd.set_option('plotting.backend', 'pandas_bokeh')
df = gpd.read_file('/home/scutum/Downloads/custom.geojson')
df.plot_bokeh(simplify_shapes=False)

**Comment by PatrikHlobil** [comment]
Hi @makermotion ,

did it work With a New Release?

Best Patrik

**Comment by makermotion** [comment]
hey @PatrikHlobil, tbh i did not try the same config with the new release.

**Comment by PatrikHlobil** [comment]
Hi @makermotion,

works fine for me:

![image](https://user-images.githubusercontent.com/31643597/114013835-46655980-9868-11eb-91ed-fe24b54010aa.png)

Tested with:
```
geopandas           0.9.0
pandas              1.2.3
pandas-bokeh        0.5.1 
bokeh               2.2.3

```

Best Patrik
