### ISSUE TITLE
Conda installation failed : HTTP 000 - Connection Failed Error

### ISSUE THREAD

**Issue by hamnas** [PatrikHlobil/Pandas-Bokeh#73]
Hi,

I have aproblem when I am trying to run the following comand to install the Pandas-Bokeh package for my Anaconda 4.8.2 + Python 3.8 for Win 64:

_conda install -c patrikhlobil pandas-bokeh_ 

I keep getting this message: 

_An HTTP error occured when trying to retrieve this URL._

Although I was able to install "Pandas-Bokeh" using a pip command, my jupyter notebook is unable to import it, giving an Error: "ModuleNotFoundError: No module named 'pandas_bokeh' "

**Comment by PatrikHlobil** [comment]
Hi @hamnas, I have a windows 10 Partition on my computer and will try to reproduce your error. Thanks for reporting the issue,

Best Patrik

**Comment by hamnas** [comment]
Hi Patrik,
Thanks! I will be waiting then...

**Comment by PatrikHlobil** [comment]
Hi @hamnas,

didn't had the time to verify so far, however there were successfull downloads for Win64 for Python3.8 on Anaconda Server
![image](https://user-images.githubusercontent.com/31643597/84469002-57613080-ac80-11ea-939b-7e6ea087b4d9.png)

Do you have a private computer with open network properties to check the issue.

Best Patrik

**Comment by hamnas** [comment]
I do have a personal computer connected to an open netweok with no proxy!
Could you please guide me through it how you did so?

**Comment by PatrikHlobil** [comment]
Hi @hamnas,

I just checked to install pandas-bokeh on my Windows 10 machine and it worked. 

Could you try to create another clean conda environment (maybe also try python 3.7) and then just install pandas-bokeh and try again.

Best Patrik

**Comment by hamnas** [comment]
Hi @PatrikHlobil ,

Thank you for the information!

As you advised, I created a new conda environment with python 3.7 and it worked!
I have no idea why it does not work on the base environment (maybe a conflict with other packages or with python version 3.8).

Thank you again!

**Comment by PatrikHlobil** [comment]
Hi @hamnas,

Great to hear that it finally worked. I never use the conda base environment Because I once installed something in there and after that the environment was broken.

Best Patrik
