### ISSUE TITLE
rotate xaxis label

### ISSUE THREAD

**Issue by eddyizm** [PatrikHlobil/Pandas-Bokeh#74]
I don't see an option to rotate the xaxis label so I'm guessing this may be a feature request instead of a bug. I'm hoping to use this instead of bokeh but so far not having any luck. 
I will continue looking into the code

**Comment by PatrikHlobil** [comment]
Hi @eddyizm,

since the feature you were searching is already available using the `vertical_xlabel=True` option, I will close the ticket.

Best Patrik
