### ISSUE TITLE
Allow specification of projection EPSG

### ISSUE THREAD

**Issue by ajkswamy** [PatrikHlobil/Pandas-Bokeh#76]
Wonderful tool!

Currently, plotting geographical data automatically uses Web Mercator projection (EPSG: 3857). It would be good to have the possibility to specify other projections as well. Thanks

**Comment by PatrikHlobil** [comment]
Hi @ajkswamy,

great to hear that you like Pandas-Bokeh. So far, Bokeh itself does not allow to use anything except Web Mercador projection as far as I know. If this is not correct, please give me the corresponding documentation resources and I try to include other projections in a next release. Thanks for the proposal,

Best Patrol

**Comment by ajkswamy** [comment]
Hi @PatrikHlobil 

You are right. It looks like all tile providers in Bokeh only provide web-mercator-projected tiles. Therefore, any plot that uses such a tiles as base will have to use web-mercator-projection. Until non-mercator tile providers are available in bokeh (I am not even sure such providers exist), it would not sense to add this option. Thanks for the discussion!
