### ISSUE TITLE
¿How I could change    xaxis.major_label_orientation ? 

### ISSUE THREAD

**Issue by akitxu** [PatrikHlobil/Pandas-Bokeh#89]
Dear all. In bokeh I could change xaxis.major_label perform `p.xaxis.major_label_orientation = math.pi/2`
¿How could I change this orientation in bokeh  Python-Boken?. Thanks for your help

**Comment by PatrikHlobil** [comment]
Hi @akitxu ,

there are 2 ways to do so:

1.) Use the `vertical_xlabel=True` option in plot_bokeh (example here: https://github.com/PatrikHlobil/Pandas-Bokeh#histogram)

2.) You can get the Bokeh figure from Pandas Bokeh via:

```python
p = df.plot_bokeh(....., show_figure=False)
```

then you can just change whatever you want on the Bokeh figure and show it:
```python
p.xaxis.major_label_orientation = math.pi/2
pandas_bokeh.
```

Hope that I could help you,

Best Patrik

**Comment by akitxu** [comment]
Patrick. phanks for your help. I have implemented the sentences that you indicate and I do not get the desired effect. This is my script. I will appreciate if you tell me what my mistake is.

`# DataFrame with dates as index
import math
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader as pdr 

from bokeh.plotting import reset_output
reset_output () 

import pandas_bokeh
pandas_bokeh.output_notebook()

start = "2016-1-4"
end = "2020-10-19"
iberdrola = pdr.DataReader("IBE.MC", "yahoo", start, end)
iberdrola = iberdrola[["Close"]]

p = figure(plot_width=400, plot_height=250, x_axis_type="datetime")
p.xaxis.major_label_orientation = math.pi/4

iberdrola.plot_bokeh.line(
    figsize=(800, 450),
    title="Cotizaciones de Iberdrola",
    xlabel="Fechas",
    ylabel="Cotizaciones [€]",
    yticks=[0, 100, 200, 300, 400],
    ylim=(0, 10),
    xlim=("2016-01-04", "2020-10-01"),
    colormap=["red", "blue", "green"],
    plot_data_points=True,
    plot_data_points_size=0.8)`

Something I am not understanding well. Something I am not understanding well. The sentences valid for Bokeh, are also valid for this package Pandas-Bokeh ?.

**Comment by PatrikHlobil** [comment]
Hi @akitxu,

you cannot mix matplotlib with bokeh, these are 2 distict plotting frameworks. 

just do:

```python
iberdrola.plot_bokeh.line(
figsize=(800, 450),
title="Cotizaciones de Iberdrola",
xlabel="Fechas",
ylabel="Cotizaciones [€]",
yticks=[0, 100, 200, 300, 400],
ylim=(0, 10),
xlim=("2016-01-04", "2020-10-01"),
colormap=["red", "blue", "green"],
plot_data_points=True,
plot_data_points_size=0.8,
vertical_xlabel=True)
```

**Comment by akitxu** [comment]
Thank you. Now I understand it better. I'm going to focus on Python-Bokeh.
