### ISSUE TITLE
RuntimeError: Models must be owned by only a single document....

### ISSUE THREAD

**Issue by akitxu** [PatrikHlobil/Pandas-Bokeh#90]
Dear Patrik, horizontal versions of stacked plot  returns the error
`RuntimeError                              Traceback (most recent call last)
<ipython-input-31-941ccdd5fd43> in <module>
     26 
     27 #Plot all barplot examples in a grid:
---> 28 pandas_bokeh.plot_grid([[p_bar, p_stacked_bar],
     29                         [p_hbar, p_stacked_hbar]], 
     30                        plot_width=450)
.........................................................................
RuntimeError: Models must be owned by only a single document, BoxZoomTool(id='6364', ...) is already in a doc`

What can be the cause? Thanks for the help

**Comment by PatrikHlobil** [comment]
Dear @akitxu ,

could you give me a  code example that reproduces this error?

Best Patrik
