### ISSUE TITLE
BokehDeprecationWarning: 'legend' keyword is deprecated

### ISSUE THREAD

**Issue by caph1993** [PatrikHlobil/Pandas-Bokeh#91]
I am getting a deprecation warning for every scatter plot I make.

You may reproduce the warning by running this code on a notebook (python 3.6):
```
import pandas as pd
import numpy as np
import pandas_bokeh
pandas_bokeh.output_notebook()
np.random.seed(0)
df=pd.DataFrame(np.random.random((100,3)), columns=['x','y','z'])
df.plot_bokeh.scatter('x', 'y', 'z', colormap='Turbo')
```
![image](https://user-images.githubusercontent.com/5473460/100394820-8429ba00-300c-11eb-8d4f-62318ce841f9.png)

The warning is: `BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead`

**Comment by PatrikHlobil** [comment]
Dear @caph1993 ,

thanks for reporting the issue. I already fixed this and when you upgrade to Pandas-Bokeh 0.5.2 the Deprecation Warning should be fixed.

Really nice plot by the way!

Best Patrik
