### ISSUE TITLE
FYI: Bokeh release 2.3 coming!

### ISSUE THREAD

**Issue by hyles-lineata** [PatrikHlobil/Pandas-Bokeh#95]
Hi pandas-bokeh!

Just a friendly heads-up from Bokeh that we plan on releasing 2.3 next week, which includes [many changes](https://github.com/bokeh/bokeh/milestone/62?closed=1). It's probably worth doing some testing of pandas-bokeh with 2.3dev, just to be sure that nothing breaks as a result of this release.

Let us know if we can answer any specific questions. Thanks!

**Comment by PatrikHlobil** [comment]
Hi @hyles-lineata ,

thanks for the note. I will run the tests again the dev version of bokeh 2.3.

best Patrik

**Comment by PatrikHlobil** [comment]
Hi @hyles-lineata ,

I indeed had to fix a minor problem that enforces a str-datatype on x- and y-labels . I will release the bugfix tonight, so there shouldn't be a problem when you are releasing Bokeh.

Best Patrik

**Comment by bryevdv** [comment]
cc @mattpap in case that change was more strict than intended

**Comment by mattpap** [comment]
It's too strict indeed. Should allow `Nullable(String)` to match `Axis`' interface.
