### ISSUE TITLE
No adaptative xaxis tick label and gridline  for X float value

### ISSUE THREAD

**Issue by leopoletti** [PatrikHlobil/Pandas-Bokeh#99]
Hello,

I have a problem with xaxis tick label and associated grid line: there is no automatic adaptation leading to display all tick label when there float number.

Hereunder the code to test it:

```python
import numpy as np
import pandas as pd
pd.set_option('plotting.backend', 'pandas_bokeh')
pd.plotting.output_notebook()

np.random.seed(42)
df = pd.DataFrame({"Google": np.random.randn(1000)+0.2, 
                   "Apple": np.random.randn(1000)+0.17}, 
                   index=np.arange(1000)*0.001)
df = df.cumsum()
df = df + 50
df.plot_bokeh(kind="line")
```

I get this output:
![image](https://user-images.githubusercontent.com/5619357/113865156-0fca0900-97ac-11eb-95f7-d5481e54bef4.png)
![image](https://user-images.githubusercontent.com/5619357/113865403-561f6800-97ac-11eb-8277-7ac7bdd174f5.png)

Do you have any idea how to handle this?

Python 3.8.8
pandas_bokeh 0.5.4
pandas 1.2.3
jupyterlab 3.0.9
notebook 6.2.0
IPython 7.21.0
jupyter-bokeh  2.0.4

OS windows7

**Comment by PatrikHlobil** [comment]
Hi @leopoletti ,

there is an xticks option in pandas-bokeh. just try for example:

```python
df.plot_bokeh(kind="line", xticks=np.arange(10)*0.1)
```

and you get 
![image](https://user-images.githubusercontent.com/31643597/113876266-dd260d80-97b7-11eb-9c8f-f515e10fad10.png)

Best Patrik

**Comment by leopoletti** [comment]
Hello Patrik,

Thank for your solution it is an helping work around but basiccaly I would like the xtick label to adapat with thz zoom in or zoom as you could could get using directly bokeh:

```python
from bokeh.plotting import figure, show

p=figure()
p.line(x=df.index,y=df.Google, legend_label="Google", color="blue",line_width=2)
p.line(x=df.index,y=df.Apple, legend_label="Apple",color="orange",line_width=2)

show(p)
```
![image](https://user-images.githubusercontent.com/5619357/114046690-580b2900-9889-11eb-8a69-5d756fae5fdd.png)
![image](https://user-images.githubusercontent.com/5619357/114046770-6a856280-9889-11eb-92e9-2540012cbf39.png)

**Comment by PatrikHlobil** [comment]
Hi @leopoletti,

thanks again for opening the issue. I think the default behaviour should be as you described it with automatic ajustment of the float xaxis. I just release a new release 0.5.5 that implemented this. Looks like this now:

![Peek 2021-04-11 19-45](https://user-images.githubusercontent.com/31643597/114315303-ad9c3b80-9afe-11eb-8f96-74d48abfdfa8.gif)

Hope you enjoy working with Pandas-Bokeh.

Best Patrik
